### ISSUE TITLE
Are the README instructions up to date?

### ISSUE THREAD

**Issue by diasdavid** [oduwsdl/ipwb#192]
I was unable to follow the instructions with success. @machawk1 do you have a hint of what could I have missed? 

![image](https://user-images.githubusercontent.com/1211152/27012978-8ee93660-4ed2-11e7-81aa-4ab16b8bb7f5.png)

![image](https://user-images.githubusercontent.com/1211152/27012980-9f7fce8a-4ed2-11e7-9579-683e32afc442.png)

**Comment by machawk1** [comment]
@diasdavid There was an old warc file referenced in the README that did not correspond to the URI that the README suggests you access. Notice the bitchmagazine.org SURTed URIs from the indexer with no mention of the `~salam` address. The instructions have been fixed in 
 https://github.com/oduwsdl/ipwb/commit/fc0b25656be265911a77bbfff9138a9ada846879 . Please give them another run-through.

As to why the replay system returned an "error" for what amounts to a 404 is a separate issue I will need to resolve.

**Comment by diasdavid** [comment]
Re-run the example and I was able to be a little bit more successful, now I can open the IPWB webpage with:

![image](https://user-images.githubusercontent.com/1211152/27095565-14de8312-5066-11e7-872e-34a256668d02.png)

I wasn't unable to open any Salam's backups from here, and I only had partial success retrieving the snapshots from the other pages.

However, I also tried using the default `sample data` by just opening with `ipwb replay` and there I was able to retrieve's Sawood webpage.

**Comment by machawk1** [comment]
@diasdavid Would you mind pulling the latest from pip and seeing if you will can't access the capture of salam's web page using the WARC source file?

**Comment by machawk1** [comment]
@diasdavid This should be resolved. @diasdavid Please re-open if you again encounter issues when you get a chance to re-test the instructions.
