### ISSUE TITLE
pip config relies on pywb master branch and not dev

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#20]
`setup.py` needs to be changed to reference the dev branch of the pywb package but pypi does not like a URI being specified there and expects a package name. Same goes for the surt dependency. The correct branch/version IS specified in requirements.txt.

**Comment by ibnesayeed** [comment]
[This link](http://stackoverflow.com/questions/3472430/how-can-i-make-setuptools-install-a-package-thats-not-on-pypi) might be helpful.

**Comment by machawk1** [comment]
Thanks, @ibnesayeed , I am looking into using `dependency_links`, which will hopefully work with the pywb branch src.

Do you recall why you created the surt dependency of git+git://github.com/rajbot/surt#egg=surt instead of simply `surt`? They look to result in the same code.

**Comment by ibnesayeed** [comment]
I think using the plain `surt` dependency would be fine. When I first used this library in another project, there was a but in it that I wanted to get fixed which was then fixed but not pushed to pip. Since then I never tracked where the pip version is headed. I think the latest release of pip is quite up-to-date and should be used instead.

**Comment by machawk1** [comment]
No longer relevant, as we are using master.
