### ISSUE TITLE
Redirection for unavailable memento neither returns a 3XX nor updates the URI

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#363]
cdc04571e5cbcf808c690d920fb043caa8693f20 with newly merged reconstructive.

`ipwb index ipwb/samples/warcs/5mementos.warc | ipwb replay` then curl (or use browser):

`curl -I http://localhost:5000/memento/10130202100001/memento.us/` return an HTTP 200. In the browser, the supposed representation http://localhost:5000/memento/10130202100001/memento.us/ is displayed despite a server-side remapping to the nearest memento. We ought to be redirecting to the closest memento, not giving the impression to the browser that a memento exists at this datetime.

/cc @ibnesayeed

**Comment by machawk1** [comment]
<img width="672" alt="screen shot 2018-01-04 at 10 10 05 pm" src="https://user-images.githubusercontent.com/2514780/34593948-11f1d58c-f19c-11e7-9d63-5f91164225ea.png">

**Comment by ibnesayeed** [comment]
I agree that it should return a redirect to the URI-M with the precise time that is recorded in the index. However, this is not something that is caused by Reconstructive integration. It is the responsibility of the replay service to return appropriate redirect. I can see that it was not implemented in the first place. Reconstructive should be capable of following server issued redirects and acknowledging the browser for the same.

This can be fixed my adding a few lines under `showMemento` method. The second line from the last where we extract `newDatetime` from the found index record, we can check whether it is same as the `datetime` extracted from the path, if not, then a redirect should be returned rather than returning `show_uri`.

**Comment by ibnesayeed** [comment]
I will look into it and see if I can send a PR.

**Comment by ibnesayeed** [comment]
The PR #365 is ready for the review.
