### ISSUE TITLE
Do not package sample files

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/ipwb#540]
Since we no longer use a default warc file for replay, there is no incentive to package all the sample files which makes the package unnecessarily big.

Also, currently there are two places where samples are stored, one under the package and the other under the test directory. Some test files use resources from both. We can consolidate them in a single folder and move it up in the hierarchy (i.e., directly under the project root).

**Comment by machawk1** [comment]
This will require recoding the paths in the Python tests to reference the new relative paths. Should we have:
* `ipwb/`
** `ipwb/` (the ipwb module code)
** `tests/`(ipwb test scripts)
** `samples/` (sample files)

...And just have the tests reference the samples from the directory in the root of the project instead of within `ipwb/ipwb/` or `ipwb/tests/`? This will also be considered when we add the ability for more refined collections with the samples (which will need corresponding tests).

**Comment by ibnesayeed** [comment]
Yes, that's the organization I am proposing here.
