### ISSUE TITLE
Cannot fetch CDXJ file from IPFS

### ISSUE THREAD

**Issue by anatoly-scherbakov** [oduwsdl/ipwb#634]
Running the following command on the current `master`:

    ipwb replay QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W

Returns this:

```
File QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W does not exist locally, fetching remote
No scheme in path, assuming IPFS hash and fetching...
Trying to ipfs.cat('QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W')
Data successfully obtained from IPFS
IPWB replay started on http://localhost:5000
 * Serving Flask app "ipwb.replay" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
```
Now, when opening http://localhost:5000, the server crashes:

```
Retrieving URI-Ms from QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W
File QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W does not exist locally, fetching remote
No scheme in path, assuming IPFS hash and fetching...
Trying to ipfs.cat('QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W')
Data successfully obtained from IPFS
a bytes-like object is required, not 'str'
(<class 'TypeError'>, TypeError("a bytes-like object is required, not 'str'"), <traceback object at 0x7f1de3dd4440>)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 593, in showLandingPage
    mementoInfo = calculateMementoInfoInIndex(iFile)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 982, in calculateMementoInfoInIndex
    lines = indexFileContents.strip().split('\n')
```

whereas the expected behavior would be to read the CDXJ file I put there before like this:

```
ipfs add stopcoronavirus-russia.1587186455.cdxj 
added QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W stopcoronavirus-russia.1587186455.cdxj
 22.29 KiB / 22.29 KiB [=================================================================================] 100.00%
```

**Comment by ibnesayeed** [comment]
I think the fetched index should be cached locally after fetching from the IPFS and use that local file for subsequent calls. An index file stored in the IPFS is not going to be mutable anyway, so there is no fear of missing any updates in the index. That said, the simple encode() call should fix the byte/str issue.

**Comment by anatoly-scherbakov** [comment]
Not quite. After adding the `.encode()` call other exceptions start to pop out:

```
[Errno 2] No such file or directory: '/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W'
(<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7f9870306f80>)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 263, in showMemento
    resolvedMemento = resolveMemento(urir, datetime)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 238, in resolveMemento
    cdxjLinesWithURIR = getCDXJLinesWithURIR(urir, indexPath)
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 304, in getCDXJLinesWithURIR
    cdxjLineIndex = getCDXJLine_binarySearch(s, indexPath, True, True)  # get i
  File "/home/anatoly/.pyenv/versions/3.8.1/envs/ipwb/lib/python3.8/site-packages/ipwb/replay.py", line 1071, in getCDXJLine_binarySearch
    with open(fullFilePath, 'r') as cdxjFile:
```

To reproduce, you can do this:

```
git checkout c980dc187be7643b7d831d1419e27c01f1dcfb75
pip install -U .
ipwb replay QmReQCtRpmEhdWZVLhoE3e8bqreD8G3avGpVfcLD7r4K6W
```

then, open localhost:5000 and click the single HTML link the page suggests.

What I tried to do is to optimize for performance by caching file in memory; you suggest to optimize by RAM by caching it on disk. Both strategies are probably viable for different circumstances. For example, if ipwb was ever used for production purposes, RAM caching would be a useful feature to avoid killing the performance with expensive disk calls.

What if this was configurable instead?

**Comment by ibnesayeed** [comment]
> What if this was configurable instead?

Any configuration would bring added complexity and points of failures, so it should be considered with caution. If we implement disk caching, the same system can be leverage for memory caching by simply introducing tmpfs (some times called RAMFS) transparently, but the transforming of objects in memory on disc is not going to be that straightforward and efficient.

**Comment by anatoly-scherbakov** [comment]
Yes, but tmpfs requires some system level configuration and maintenance on the user's part. Caching file contents in a Python `dict` is, on the other hand, fairly easy.

**Comment by ibnesayeed** [comment]
Binary search on file is usually fast enough even on usual disk to outweigh any memory-based implementation in situations like these. Here are some reasons to support my rationale:

* A dictionary-based two-tier index will have slightly worse than constant-time lookup complexity, which is great, but it will come with a little worse than linear space complexity which is not good. For example, a one MB of index file on disk, when parsed and loaded as a data structure of objects will take more space than its raw form due to the overhead of object pointers, hash tables, and whatnot. This might work for small collections, but will not scale, on the contrary, a file-based solution scales nicely and performs equally well on smaller collections.
* Our study shows only a small portion of the archive is ever accessed by users, which means a lot of memory space will be occupied for the entire session of the server for no good use.
* Binary search comes with a logarithmic time complexity (space complexity doesn't matter as much in file-based index), which means each time the number of records in the index is doubled, lookup cost increases by just one extra disk read.
* Our study shows that of the small percentage of the whole collection that is accessed by users, some resources are accessed way more often, which means, a simple LRU caching in the binary search on file can dramatically cut down the lookup cost.
* An LRU cache on the binsearch function will not only benefit popular resources but will cut down top-few levels of the binary tree (i.e., mid of the file, mids of the first and last halves of the file and so on) for each lookup, as those paths of the binsearch tree will be frequently traversed.
* The last few levels of the binsearch tree may not cause as many disk read anyway, because the underlying file system reads data from the disk in blocks that may contain a handful of consecutive lines in which the binary search will be performed towards the leaf of the lookup tree unless it crosses the block boundary.

With these things in mind, I do not think it is a good idea to invest resources and introduce complexity in devising a non-scalable solution branch for small collections, but I am open to discussion and gaining insights from other perspectives.

**Comment by anatoly-scherbakov** [comment]
I see your rationale, everything is logical.

> A dictionary-based two-tier index will have slightly worse than constant-time lookup complexity, which is great, but it will come with a little worse than linear space complexity which is not good

Are you sure? AFAIK search time in `dict` by key is logarithmic. Search by datetime in the datetimes list will be probably linear though. I am not certain whether, say, `numpy` provides more optimized data structures for such a use case like inexact searching by datetime.

But this is all implementation detail. I believe they can be propagated to individual backends.

I will look into changing my PR to both fix reading from IPFS and avoid cache-everything-in-RAM-and-not-care strategy.

**Comment by machawk1** [comment]
Good catch with this feature being broken, @anatoly-scherbakov. I do not think it is well tested and thus fell by the wayside when we moved to pure Py3 and neglected to update this str/byte code path.

Is #635 ready for further review per your last comment?

**Comment by anatoly-scherbakov** [comment]
@machawk1 no, not yet. I will remove the mandatory in-memory cache and request review again; will do it this week hopefully.

**Comment by ibnesayeed** [comment]
> Are you sure? AFAIK search time in `dict` by key is logarithmic.

Yes, I am sure about dictionary look up being a constant time operation in theory. That's the role of the hash function and hash table to find the hash of the key and jump to the potential record location directly. However, in practical the performance is a little worse than constant time due to collisions that cause linear probing until a match is found. This overhead of linear probing is reduced by resizing the hash table after certain collision ratio limit, which comes with the cost of insertion delays, more seriously noticed when dictionary grows big in size. Logarithmic complexity usually shows up whenever there is recursive division of the look up space (such as binary search, that happens on a sorted list).

> Search by datetime in the datetimes list will be probably linear though.

This can be linear or logarithmic (if you sort those elements and implement binary search in it), but the impact will be small, unless there are too many copies of a handful of frequently accessed resources.

**Comment by anatoly-scherbakov** [comment]
> Yes, I am sure about dictionary look up being a constant time operation in theory.

I see. I knew dictionary is a hash table inside, but I am not versed well enough with its properties though I've been using Python for quite a few years already :)

Thank you for merging the PR @machawk1. Should this issue be closed?

**Comment by machawk1** [comment]
@anatoly-scherbakov [Here](https://wiki.python.org/moin/TimeComplexity) is a reference to the time complexity of different operations on Python data structures, which appears to align with @ibnesayeed assessment.

Also, yes, this issue should be closed.
