### ISSUE TITLE
Update Check reports "None" if no net access is available

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#700]
I turned off my networks connections and ran `ipwb --update-check` with the latest master (ee489ed) installed and was returned:

```
* Latest version: None
* Installed version: None
```
...despite the version of ipwb being installed. Something is amiss with the method to check the installed version but we could also report the inability to check the remote location due to the inability to access it. This would also help if pypi.org went down.

**Comment by ibnesayeed** [comment]
I anticipated this issue when I was reviewing your PR and was about to suggest at least three different messages in three different situations, but it would have changed some conditionals and indentation, so I decided to not mention it. You are getting `None` here because when latest version check fails, the function returns a tuple `(None, None)`, if I remember correctly.

**Comment by machawk1** [comment]
That is correct, @ibnesayeed. I am testing a solution now. PR to come.
