### ISSUE TITLE
Evaluate potential pros/cons of upgrading ipwb's Flask dependency to 2.0

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#728]
Is there any new functionality ipwb can leverage? Would it require a significant overhaul of the ipwb codebase? Are there particular Flask performance benefits that would be translated into ipwb performance benefits?

Released May 11, 2021.

https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-1

**Comment by Luflosi** [comment]
One pro of upgrading the Flask dependency is that packaging becomes a lot simpler. Many repositories have only the latest version of most packages, so adding ipwb to them becomes a lot harder because Flask has the wrong version and one would need to add a second legacy flask version to the repo as well.
